### PR TITLE
Kureshi 2020 Update

### PR DESCRIPTION
**Pull request by danejo3**
The purpose of this PR is to resolve #90 .

The Kureshi 2020 paper has 20 markers recorded on, page 5,  figure Table 1. All markers have been recorded and placed in the `MicroHapDB/dbbuild/sources/kureshi2020` directory to build the latest MicroHap database.

image

### CODE REVIEW

**Comment by danejo3** [comment]
Just to record this here.

The following Microhap markers are found in both “Jin2020” and “Kureshi2020” papers/sources.
- mh04ZHA-004
- mh07ZHA-003
- mh16ZHA-009
- mh19ZHA-007
- mh19ZHA-009

**Comment by danejo3** [comment]
Database is update to date and tests passing. Ready for review!

**Comment by rnmitchell** [comment]
> Just to record this here.
> 
> The following Microhap markers are found in both “Jin2020” and “Kureshi2020” papers/sources.
> 
> * mh04ZHA-004
> * mh07ZHA-003
> * mh16ZHA-009
> * mh19ZHA-007
> * mh19ZHA-009

I think you mean Sun2020 not Jin2020.

**Comment by danejo3** [comment]
> > Just to record this here.
> > The following Microhap markers are found in both “Jin2020” and “Kureshi2020” papers/sources.
> > 
> > * mh04ZHA-004
> > * mh07ZHA-003
> > * mh16ZHA-009
> > * mh19ZHA-007
> > * mh19ZHA-009
> 
> I think you mean Sun2020 not Jin2020.

Yup! You're right!

**Comment by rnmitchell** [comment]
Do you want me to review the @standage or did you want to do it?

**Comment by standage** [comment]
I'll take care of it, @rnmitchell. Thanks. I haven't been receiving all notifications on this repo, so I didn't even know you guys had created PRs!

**Comment by standage** [comment]
Hey @RyanBerger98, the collection described in Sun 2020 (#84, #87) described 36 markers, including 6 KK markers, 5 ZHA markers shared with this collection, and 25 unique ZHA markers. Double checking just now, it looks like you didn't include the KK and shared ZHA markers when you prepared the Sun 2020 data. Is that right?

**Comment by standage** [comment]
@RyanBerger98 Nope, just wanted to make sure. I can't remember how precisely the dbbuild process handles markers with redundant definitions. But the question is moot if these markers are only defined in one place.

**Pull request merged**
